server:
  port: 9002

Spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: localhost:8848


management:
  endpoint:
    web:
      exposure:
        include: '*'
